version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: college
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/student_dump.sql:/docker-entrypoint-initdb.d/student_dump.sql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student_api_app
    environment:
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: college
      DB_HOST: db
      SERVER_PORT: 8080
      JWT_SECRET_KEY: secret
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql-data:
